version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(dev-deps)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
